CREATE TABLE edge (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, length INT NOT NULL, phase INT NOT NULL, start_id INT NOT NULL, end_id INT NOT NULL, supermarket_id INT DEFAULT NULL, INDEX IDX_7506D366623DF99B (start_id), INDEX IDX_7506D366E2BD8A10 (end_id), INDEX IDX_7506D366933DE57C (supermarket_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`;
CREATE TABLE food_category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`;    
CREATE TABLE food_item (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, side SMALLINT DEFAULT NULL, edge_id INT DEFAULT NULL, category_id INT DEFAULT NULL, INDEX IDX_AA3C8DCF696D413E (edge_id), INDEX IDX_AA3C8DCF12469DE2 (category_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`;
CREATE TABLE list_item (id INT AUTO_INCREMENT NOT NULL, quantity INT DEFAULT NULL, notes VARCHAR(255) DEFAULT NULL, picked TINYINT NOT NULL, picked_at DATETIME DEFAULT NULL, shopping_list_id INT NOT NULL, food_item_id INT NOT NULL, INDEX IDX_5AD5FAF723245BF9 (shopping_list_id), INDEX IDX_5AD5FAF75DF08E66 (food_item_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`;
CREATE TABLE node (id INT AUTO_INCREMENT NOT NULL, number INT NOT NULL, x_value INT DEFAULT NULL, y_value INT DEFAULT NULL, supermarket_id INT DEFAULT NULL, INDEX IDX_857FE845933DE57C (supermarket_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`;
CREATE TABLE owner_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`;       
CREATE TABLE product_location (id INT AUTO_INCREMENT NOT NULL, aisle_position SMALLINT DEFAULT NULL, food_item_id INT NOT NULL, supermarket_id INT NOT NULL, edge_id INT NOT NULL, INDEX IDX_952EE35C5DF08E66 (food_item_id), INDEX IDX_952EE35C933DE57C (supermarket_id), INDEX IDX_952EE35C696D413E (edge_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`;
CREATE TABLE shopping_list (id INT AUTO_INCREMENT NOT NULL, date_created DATETIME DEFAULT NULL, date_completed DATETIME DEFAULT NULL, date_modified DATETIME DEFAULT NULL, supermarket_id INT DEFAULT NULL, INDEX IDX_3DC1A459933DE57C (supermarket_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`;
CREATE TABLE supermarket (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, entrance_node_id INT DEFAULT NULL, INDEX IDX_D51643A2E393F4C1 (entrance_node_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`;
ALTER TABLE edge ADD CONSTRAINT FK_7506D366623DF99B FOREIGN KEY (start_id) REFERENCES node (id);
ALTER TABLE edge ADD CONSTRAINT FK_7506D366E2BD8A10 FOREIGN KEY (end_id) REFERENCES node (id);
ALTER TABLE edge ADD CONSTRAINT FK_7506D366933DE57C FOREIGN KEY (supermarket_id) REFERENCES supermarket (id);
ALTER TABLE food_item ADD CONSTRAINT FK_AA3C8DCF696D413E FOREIGN KEY (edge_id) REFERENCES edge (id);
ALTER TABLE food_item ADD CONSTRAINT FK_AA3C8DCF12469DE2 FOREIGN KEY (category_id) REFERENCES food_category (id);
ALTER TABLE list_item ADD CONSTRAINT FK_5AD5FAF723245BF9 FOREIGN KEY (shopping_list_id) REFERENCES shopping_list (id);
ALTER TABLE list_item ADD CONSTRAINT FK_5AD5FAF75DF08E66 FOREIGN KEY (food_item_id) REFERENCES food_item (id);
ALTER TABLE node ADD CONSTRAINT FK_857FE845933DE57C FOREIGN KEY (supermarket_id) REFERENCES supermarket (id);
ALTER TABLE product_location ADD CONSTRAINT FK_952EE35C5DF08E66 FOREIGN KEY (food_item_id) REFERENCES food_item (id);
ALTER TABLE product_location ADD CONSTRAINT FK_952EE35C933DE57C FOREIGN KEY (supermarket_id) REFERENCES supermarket (id);
ALTER TABLE product_location ADD CONSTRAINT FK_952EE35C696D413E FOREIGN KEY (edge_id) REFERENCES edge (id);
ALTER TABLE shopping_list ADD CONSTRAINT FK_3DC1A459933DE57C FOREIGN KEY (supermarket_id) REFERENCES supermarket (id);
ALTER TABLE supermarket ADD CONSTRAINT FK_D51643A2E393F4C1 FOREIGN KEY (entrance_node_id) REFERENCES node (id);

ALTER TABLE supermarket ADD image_path VARCHAR(255) DEFAULT NULL, ADD length INT DEFAULT NULL, ADD width INT DEFAULT NULL;

INSERT INTO `node` (`id`, `x_value`, `y_value`, `supermarket_id`) VALUES
(1, NULL, NULL, 1),
(2, NULL, NULL, 1),
(3, NULL, NULL, 1),
(4, NULL, NULL, 1),
(5, NULL, NULL, 1),
(6, NULL, NULL, 1),
(7, NULL, NULL, 1),
(8, NULL, NULL, 1),
(9, NULL, NULL, 1),
(10, NULL, NULL, 1),
(11, NULL, NULL, 1),
(12, NULL, NULL, 1),
(13, NULL, NULL, 1),
(14, NULL, NULL, 1),
(15, NULL, NULL, 1),
(16, NULL, NULL, 1),
(17, NULL, NULL, 1),
(18, NULL, NULL, 1),
(19, NULL, NULL, 1),
(20, NULL, NULL, 1),
(21, NULL, NULL, 1),
(22, NULL, NULL, 1),
(23, NULL, NULL, 1),
(24, NULL, NULL, 1),
(25, NULL, NULL, 1),
(26, NULL, NULL, 1),
(27, NULL, NULL, 1),
(28, NULL, NULL, 1),
(29, NULL, NULL, 1),
(30, NULL, NULL, 1),
(31, NULL, NULL, 1),
(32, NULL, NULL, 1),
(33, NULL, NULL, 1),
(34, NULL, NULL, 1),
(35, NULL, NULL, 1),
(36, NULL, NULL, 1),
(37, NULL, NULL, 1),
(38, NULL, NULL, 1),
(39, NULL, NULL, 1),
(40, NULL, NULL, 1),
(41, NULL, NULL, 1),
(42, NULL, NULL, 1),
(43, NULL, NULL, 1),
(44, NULL, NULL, 1),
(45, NULL, NULL, 1),
(46, NULL, NULL, 1),
(47, NULL, NULL, 1),
(48, NULL, NULL, 1),
(49, NULL, NULL, 1),
(50, NULL, NULL, 1),
(51, NULL, NULL, 1),
(52, NULL, NULL, 1),
(53, NULL, NULL, 1),
(54, NULL, NULL, 1),
(55, NULL, NULL, 1),
(56, NULL, NULL, 1),
(57, NULL, NULL, 1),
(58, NULL, NULL, 1),
(59, NULL, NULL, 1),
(60, NULL, NULL, 1),
(61, NULL, NULL, 1),
(62, NULL, NULL, 1),
(63, NULL, NULL, 1),
(64, NULL, NULL, 1),
(65, NULL, NULL, 1),
(66, NULL, NULL, 1),
(67, NULL, NULL, 1),
(68, NULL, NULL, 1),
(69, NULL, NULL, 1),
(70, NULL, NULL, 1),
(71, NULL, NULL, 1),
(72, NULL, NULL, 1);

-- docker exec -i shopmate-db mysqldump -u matt -p404404 shopmate > backup.sql
-- docker exec -i shopmate-db mysql -u matt -p404404 shopmate < backup.sql